const amendments=window.AMENDMENTS;
const generic={
 Support:["It appears likely to improve public safety.","It improves accountability, traceability or administrative clarity.","The requirement appears reasonable and proportionate."],
 Oppose:["There is insufficient evidence that the change will improve public safety.","It may unfairly burden lawful firearm owners or businesses.","A more targeted or practical alternative should be considered."],
 Unsure:["More detail or evidence is required before I can form a final view.","The likely practical impacts, costs and transition arrangements are unclear.","Definitions, exemptions or implementation details need clarification."],
 "No comment":[]
};
const KEY="tas-firearms-submission-builder-v2";
let state={current:0,answers:Array.from({length:21},()=>({position:"",reasons:[],otherReason:"",comments:""})),details:{},suggestions:"",closing:""};
const $=id=>document.getElementById(id);
function save(){state.details={name:$("name").value,town:$("town").value,email:$("email").value,background:$("background").value};state.suggestions=$("suggestions").value;state.closing=$("closing").value;localStorage.setItem(KEY,JSON.stringify(state));progress()}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.answers?.length===21)state=s}catch{};["name","town","email","background"].forEach(k=>$(k).value=state.details?.[k]||"");$("suggestions").value=state.suggestions||"";$("closing").value=state.closing||""}
function show(id){["welcome","details","amendmentCard","finalComments","review","result"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden");$("progressWrap").classList.toggle("hidden",id==="welcome");scrollTo({top:0,behavior:"smooth"})}
function progress(){const n=state.answers.filter(a=>a.position).length;$("progressBar").style.width=`${n/21*100}%`;$("progressLabel").textContent=`${n} of 21 answered`;$("stepLabel").textContent=`Amendment ${Math.min(state.current+1,21)} of 21`}
function reasonsFor(item,pos){return [...(item[pos.toLowerCase()]||[]),...(generic[pos]||[])].filter((x,i,a)=>a.indexOf(x)===i)}
function render(){const i=state.current,item=amendments[i],a=state.answers[i];$("amendmentNumber").textContent=`Amendment ${i+1} of 21`;$("amendmentTitle").textContent=item.title;$("proposal").textContent=item.proposal;$("plain").textContent=item.plain;$("current").textContent=item.current;$("change").textContent=item.change;$("impact").textContent=`${item.scope} change`;$("impact").className=`impact impact-${item.scope}`;
 $("positionOptions").innerHTML=["Support","Oppose","Unsure","No comment"].map(p=>`<button class="option ${a.position===p?"active":""}" data-p="${p}">${p}</button>`).join("");
 $("positionOptions").querySelectorAll("button").forEach(b=>b.onclick=()=>{a.position=b.dataset.p;if(a.position==="No comment"){a.reasons=[];a.otherReason=""}save();render()});
 const rs=reasonsFor(item,a.position);$("reasonArea").classList.toggle("hidden",!rs.length);$("reasonHeading").textContent=a.position?`Optional reasons to ${a.position.toLowerCase()}`:"Optional suggested reasons";
 $("reasonOptions").innerHTML=rs.map(r=>`<label class="reason"><input type="checkbox" ${a.reasons.includes(r)?"checked":""}><span></span></label>`).join("");
 [...$("reasonOptions").children].forEach((lab,idx)=>{lab.querySelector("span").textContent=rs[idx];const c=lab.querySelector("input");c.onchange=()=>{a.reasons=[...$("reasonOptions").querySelectorAll("input:checked")].map(x=>x.parentElement.querySelector("span").textContent);save()}});
 $("otherReason").value=a.otherReason||"";$("extraComments").value=a.comments||"";$("otherReason").oninput=e=>{a.otherReason=e.target.value;save()};$("extraComments").oninput=e=>{a.comments=e.target.value;save()};
 $("previousAmendment").textContent=i===0?"Back to details":"Back";$("nextAmendment").textContent=i===20?"Further suggestions":"Next";progress()}
function missing(){return state.answers.map((a,i)=>a.position?null:i+1).filter(Boolean)}
function missingModal(){const m=missing();$("missingList").innerHTML="<strong>Unanswered:</strong><br>"+m.map(n=>`Amendment ${n}`).join("<br>");$("modal").classList.remove("hidden")}
function review(){save();if(missing().length)return missingModal();$("reviewSummary").innerHTML=`<div class="summary-row"><span>Personal details</span><strong>${Object.values(state.details).some(Boolean)?"Added":"Optional"}</strong></div><div class="summary-row"><span>Amendments completed</span><strong class="complete">21 of 21</strong></div><div class="summary-row"><span>Further suggestions</span><strong>${state.suggestions?"Added":"None"}</strong></div>`;const counts={Support:0,Oppose:0,Unsure:0,"No comment":0};state.answers.forEach(a=>counts[a.position]++);$("positionTotals").innerHTML=Object.entries(counts).map(([k,v])=>`<div><strong>${v}</strong>${k}</div>`).join("");show("review")}
function generate(){if(missing().length)return missingModal();const d=state.details,L=["Submission: Firearms Amendment (Miscellaneous) Bill 2026 consultation","","To Strategy and Support, Department of Police, Fire and Emergency Management,","","I have reviewed the proposed amendments and provide the following individual submission.",""];if(Object.values(d).some(Boolean)){L.push("ABOUT ME");if(d.name)L.push("Name: "+d.name);if(d.town)L.push("Location: "+d.town);if(d.email)L.push("Email: "+d.email);if(d.background)L.push("Background or interest: "+d.background);L.push("")}L.push("COMMENTS ON THE PROPOSED AMENDMENTS","");
 state.answers.forEach((a,i)=>{const x=amendments[i];L.push(`${i+1}. ${x.title}`,x.proposal,`Position: ${a.position}`);if(a.reasons.length||a.otherReason){L.push("Reasons:");a.reasons.forEach(r=>L.push("- "+r));if(a.otherReason)L.push("- "+a.otherReason)}if(a.comments)L.push("Additional comments: "+a.comments);L.push("")});
 if(state.suggestions)L.push("FURTHER SUGGESTIONS",state.suggestions,"");if(state.closing)L.push("CLOSING COMMENTS",state.closing,"");L.push("Thank you for considering my submission.");if(d.name)L.push("","Kind regards,",d.name);$("output").value=L.join("\n");show("result")}
$("startBtn").onclick=()=>show("details");$("beginAmendments").onclick=()=>{save();state.current=0;render();show("amendmentCard")};document.querySelector("[data-back]").onclick=()=>show("welcome");
$("previousAmendment").onclick=()=>{save();if(!state.current)show("details");else{state.current--;render()}};$("nextAmendment").onclick=()=>{save();if(state.current===20)show("finalComments");else{state.current++;render()}};
$("backToLast").onclick=()=>{save();state.current=20;render();show("amendmentCard")};$("reviewBtn").onclick=review;$("editBtn").onclick=()=>{state.current=0;render();show("amendmentCard")};$("generateBtn").onclick=generate;
$("modalContinue").onclick=()=>{const m=missing();$("modal").classList.add("hidden");state.current=(m[0]||1)-1;render();show("amendmentCard")};$("modalClose").onclick=()=>$("modal").classList.add("hidden");
$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("output").value)}catch{$("output").select();document.execCommand("copy")}$("copyStatus").textContent="Submission copied to clipboard."};
$("emailBtn").onclick=()=>{const to="submissions.strategy.support@DPFEM.tas.gov.au",sub=encodeURIComponent("Submission – Firearms Amendment (Miscellaneous) Bill 2026"),body=encodeURIComponent($("output").value);location.href=`mailto:${to}?subject=${sub}&body=${body}`};
$("clearBtn").onclick=()=>{if(confirm("Clear all saved answers on this device?")){localStorage.removeItem(KEY);location.reload()}};
["name","town","email","background","suggestions","closing"].forEach(id=>$(id).addEventListener("input",save));load();progress();